### ISSUE TITLE
Multiple comment lines between imports causes transpile to fail

### ISSUE THREAD

**Issue by nicotroia** [benyap/resolve-tspaths#311]
After running tsc to compile my app, the `dist/app.js` imports look like this:
```
var calendar_edits_1 = __importDefault(require("@/routes/calendar-edits"));
var v2_1 = __importDefault(require("@/routes/calendar/v2"));
// import chatMessagesRoutes from "@/routes/chat-messages";
// import chatsRoutes from "@/routes/chats";
var client_meta_1 = __importDefault(require("@/routes/client-meta"));
var client_options_1 = __importDefault(require("@/routes/client-options"));
```

After running `resolve-tspaths`, I get:
```
var calendar_edits_1 = __importDefault(require("@/routes/calendar-edits"));
var v2_1 = __importDefault(require("@/routes/calendar/v2"));
// import chatMessagesRoutes from "./routes/chat-messages.js";
// import chatsRoutes from "./routes/chats.js";
var client_meta_1 = __importDefault(require("./routes/client-meta"));
var client_options_1 = __importDefault(require("./routes/client-options"));
```
As you can see, for some reason it only transpiles the bottom-half of the imports list.

If i REMOVE the two commented imports:
```
var calendar_1 = __importDefault(require("@/routes/calendar"));
var v2_1 = __importDefault(require("@/routes/calendar/v2"));
var client_meta_1 = __importDefault(require("@/routes/client-meta"));
var client_options_1 = __importDefault(require("@/routes/client-options"));
```

then run `resolve-tspaths`, I get:
```
var calendar_edits_1 = __importDefault(require("./routes/calendar-edits"));
var v2_1 = __importDefault(require("./routes/calendar/v2"));
var client_meta_1 = __importDefault(require("./routes/client-meta"));
var client_options_1 = __importDefault(require("./routes/client-options"));
```
Which is now correct, as all of the imports are changed. I was struggling to figure out why suddenly my builds were failing when none of my build process had changed, and this seems to be the culprit

**Comment by benyap** [comment]
Hi @nicotroia,

Thanks for your issue. Could you please provide a sample repository where this issue is reproduced?

I've tried to replicate this behaviour as a test, but I haven't been able to do so. My tests show that all imports are being transpiled correctly, both with and without comments - so there could be something in your configuration that I haven't been able to replicate.

See [here](https://github.com/benyap/resolve-tspaths/blob/2ff72356454ab6b88f91f70ff60d9e1c307b9a2e/test/steps/generateChanges.test.ts#L646-L690) for the test, and [here](https://github.com/benyap/resolve-tspaths/blob/2ff72356454ab6b88f91f70ff60d9e1c307b9a2e/test/fixtures/change/out/nested/comments.js) for the source file.
