### ISSUE TITLE
if tsc throw errors , resolve-tspaths does not continue handle paths

### ISSUE THREAD

**Issue by evgen-kent** [benyap/resolve-tspaths#345]
IT might be good if resolve-tspaths continue resolving the paths

**Comment by benyap** [comment]
Hey @evgen-kent, you'll need to provide more details.

`resolve-tspaths` does not run `tsc` so I'm not quite sure what you mean.

**Comment by evgen-kent** [comment]
`"build": "rm -rf bin && tsc -p tsconfig.json && resolve-tspaths",
    "start": "node ./bin/src/www",`
    
    I have the following scripts in my package.json
    and I notice if tsc command cause any errors , then  `resolve-tspaths` does not handle any path.
    
    the js file is generated but the path aliases does not replaced, if I put `//ts-ignore` for example or fix the errors everything is  OK

**Comment by benyap** [comment]
Hi @evgen-kent, because you are using the [&& operator](https://stackoverflow.com/a/30508672) in your script, `resolve-tspaths` will only run if `tsc` does not fail.

This is not related to how `resolve-tspaths` works, but rather how you've set up your build script. You'll need to change your build script if you want the behaviour you described.

Hope this helps - I will close this since this isn't an issue that can be addressed by `resolve-tspaths`.
